put MECAT hooks in

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,19 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-# This file is part of Command and Data Handeling Git Hooks.
-#
-# Command and Data Handeling Git Hooks is free software: you can
-# redistribute it and/or modify it under the terms of the GNU General
-# Public License as published by the Free Software Foundation, either
-# version 3 of the License, or (at your option) any later version.
-#
-# Command and Data Handeling Git Hooks is distributed in the hope that it
-# will be useful, but WITHOUT ANY WARRANTY; without even the implied
-# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-
-# You should have received a copy of the GNU General Public License
-# along with CDH test assignmen.  If not, see <http://www.gnu.org/licenses/>.
+echo "Running pre-commit hook"
 
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
@@ -23,4 +10,21 @@ else
 	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
 
-.git/hooks/check-style
+#Make sure it builds first - we're not big enough for CI 
+
+#float up in MECAT until you're in root dir 
+while [ "basename $(realpath $(dirname .))" -ne "MECAT" ]; do
+    cd ..
+done
+
+#compile test
+make -j 8
+if [ $? -ne 0 ]; then
+    echo "Make failed. Commit aborted" 
+    exit 1
+fi
+
+#output validity test
+
+# If there are whitespace errors, print the offending file names and fail.
+exec git diff-index --check --cached $against --
